-- =====================================================================
--  集装箱拖车记录表 模拟数据 (PostgreSQL) —— 提空箱登记
--
--  执行前提(缺一不可, 因为记录要引用箱号和拖车号):
--    1. initial.sql              —— container_trailer_record 表和触发器已存在
--    2. container-data.sql       —— 箱号 CSNU1234567 等已存在
--    3. trailer-data.sql         —— 拖车号 沪A12345 等已存在
--
--  8 条提空箱记录, 覆盖了列表和筛选需要验证的情况:
--    · 按箱号前缀筛:  containerNo=CSNU → 命中 **2 条**(id 1、7, 同一个箱提了两次)
--    · 按拖车号前缀筛: trackNo=沪A     → 命中 **2 条**(id 1、8, 同一辆车跑了两次)
--    · 按进场时间区间: 2026-10-01 ~ 2026-10-08 → 命中 **5 条**(id 4、5、6、7、8)
--    · 出场时间可以留空: id 5、7、8 是**还没出场**的(dc_out_date 为 null),
--                       用来验证前端对空时间的处理
--
--  ⚠️ 所有箱号和拖车号都取自上面两个种子文件, 对得上, 所以"箱号/拖车号必须存在"
--     那道校验能通过。
--
--  编写约定:
--    1. insert_time / update_time 不写值, 留 null 交给 set_time_fields() 触发器。
--       (dc_in_date / dc_out_date 是业务字段, 由本脚本显式给值。)
--    2. id 显式指定 + on conflict do nothing, 保证脚本可以重复执行。
--    3. id 是 generated by default as identity: 显式插入 id 不会推进自增序列,
--       所以末尾必须把序列对齐到 max(id) + 1。
-- =====================================================================

begin;

insert into container_trailer_record (id, container_no, track_no, dc_in_date, dc_out_date, use_note) values
    (1, 'CSNU1234567', '沪A12345', '2026-09-10 08:30:00', '2026-09-10 14:20:00', '空箱提取'),
    (2, 'CSNU7654321', '沪B67890', '2026-09-18 09:00:00', '2026-09-18 16:40:00', '装货前检查'),
    (3, 'TGHU9876543', '浙B23456', '2026-09-25 07:45:00', '2026-09-25 12:10:00', '租箱'),
    (4, 'MSKU1234565', '粤B34567', '2026-10-02 10:15:00', '2026-10-02 18:00:00', '冷藏箱预冷'),
    (5, 'MSCU2345671', '鲁B45678', '2026-10-05 08:00:00', null,                  '尚未出场'),
    (6, 'CMAU3456783', '津A56789', '2026-10-07 13:30:00', '2026-10-07 19:25:00', '危险品专用'),
    (7, 'CSNU1234567', '闽D67890', '2026-10-08 09:10:00', null,                  '第二次提箱'),
    (8, 'TGHU9876543', '沪A12345', '2026-10-08 14:00:00', null,                  null)
on conflict do nothing;

-- 显式插入 identity 列不会移动序列, 这里手动同步。
-- setval(..., n, false) 表示下一次 nextval 返回 n, 所以取 max(id) + 1。
select setval(
    pg_get_serial_sequence('container_trailer_record', 'id'),
    coalesce((select max(id) from container_trailer_record), 0) + 1,
    false
);

commit;
