-- =====================================================================
--  客户状态字典 初始数据 (PostgreSQL)
--
--  执行前提: 已执行 initial.sql —— customer_status 表和 set_time_fields()
--            触发器都必须已经存在, 本脚本不负责建表。
--
--  写入三条客户状态, id 显式指定为 1 / 2 / 3, 与 Customer_Status 的列注释
--  "1正常, 2异常, 3注销" 以及后续业务里 customer.status_id 的取值保持一致。
--
--  客户表的样本数据在 customer-data.sql (依赖本脚本写入的 1/2/3)。
--
--  编写约定:
--    1. insert_time / update_time 不写值, 留 null 交给 set_time_fields() 触发器
--       填北京时间, 与后端 CustomerStatusServiceImpl.create() 的行为一致。
--    2. 用 on conflict do nothing, 保证脚本可以重复执行 —— 重复跑不会报唯一键冲突。
--    3. id 是 generated by default as identity: 显式插入 id 不会推进自增序列,
--       所以末尾必须把序列对齐到 max(id) + 1, 否则后端新增状态时会生成 id=1 并撞主键。
-- =====================================================================

begin;

insert into customer_status (id, description) values
    (1, '正常'),
    (2, '异常'),
    (3, '注销')
on conflict do nothing;

-- 显式插入 identity 列不会移动序列, 这里手动同步。
-- setval(..., n, false) 表示下一次 nextval 返回 n, 所以取 max(id) + 1。
select setval(
    pg_get_serial_sequence('customer_status', 'id'),
    coalesce((select max(id) from customer_status), 0) + 1,
    false
);

commit;
