-- =====================================================================
--  航运项目 数据库初始化脚本 (PostgreSQL)
--  依据《第六周报告》中定义的关系模式与数据字典编写
--
--  编写约定:
--    1. 报告中的 datetime 统一映射为 timestamp。
--    2. 报告中标注的"逻辑外键"仅记录关联关系, 不建立物理外键约束,
--       因此本脚本不含 foreign key, 关联关系通过 comment 与末尾索引体现。
--    3. 自增主键使用 SQL 标准语法 generated by default as identity,
--       未使用 PostgreSQL 专有的 serial / bigserial。
--    4. insert_time / update_time 不设默认值(原 default current_timestamp 已移除),
--       由后端在写入时自行赋值, 避免依赖数据库服务器时区。
--    5. 报告中的 Order、User 两个表名都是 SQL 保留字, 实际建表改名为
--       Orders、Users, 因此无需加双引号。
--    6. GT / NT / DWT / timezone_UTC8 / timezone_Asia_Shanghai 是报告里定义的
--       字段名(不是关键字), 为与报告保持一致仍保留原有大小写, 所以需要双引号。
--    7. 除主键与时间字段外, 业务字段是否 not null 由应用层校验。
--       例外: Cargo 的 cargo_type_id / order_id / quantity, 以及
--       Cargo_Container_Result 的 cargo_id / container_no / quantity 直接建了 not null ——
--       这几列是记录本身的必需信息(挂哪个订单、什么种类、多少件、装进哪个箱),
--       缺一个这条记录就没有意义, 所以让数据库也兜一道, 不只靠应用层。
--    8. insert_time / update_time 由 set_time_fields() 触发器维护, 规则见文件末尾。
--       该触发器函数使用 plpgsql 编写, 是 PostgreSQL 专有语法。
-- =====================================================================

begin;

-- =====================================================================
-- 1. 客户信息管理
-- =====================================================================

-- 关系模式: Customer(id, name, phone, email, address,
--                   qualification, qualification_valid_to, status_id)
create table Customer (
    id                      bigint      generated by default as identity primary key,
    name                    varchar(50),
    phone                   varchar(30),
    email                   varchar(50),
    address                 varchar(255),
    qualification           varchar(100),
    qualification_valid_to  timestamp,
    status_id               bigint,
    insert_time             timestamp   not null,
    update_time             timestamp   not null
);
comment on table  Customer                         is '客户信息表';
comment on column Customer.id                      is '客户ID';
comment on column Customer.name                    is '客户名称';
comment on column Customer.phone                   is '联系方式';
comment on column Customer.email                   is '电子邮箱';
comment on column Customer.address                 is '详细地址';
comment on column Customer.qualification           is '资质信息';
comment on column Customer.qualification_valid_to  is '资质有效期至';
comment on column Customer.status_id               is '客户状态ID, 逻辑外键 -> Customer_Status.id';
comment on column Customer.insert_time             is '创建时间';
comment on column Customer.update_time             is '修改时间';

-- 关系模式: Customer_Status(id, description)
create table Customer_Status (
    id            bigint      generated by default as identity primary key,
    description   varchar(50) unique,
    insert_time   timestamp   not null,
    update_time   timestamp   not null
);
comment on table  Customer_Status              is '客户状态字典表';
comment on column Customer_Status.id           is '状态ID';
comment on column Customer_Status.description  is '状态描述: 1正常, 2异常, 3注销, 其他自定义';
comment on column Customer_Status.insert_time  is '创建时间';
comment on column Customer_Status.update_time  is '修改时间';

-- =====================================================================
-- 2. 订单信息管理
-- =====================================================================

-- 关系模式: Order(id, customer_id, order_date,
--                 loading_port_id, discharge_port_id, status_id)
-- 注意: 报告中表名为 Order, 为避免 SQL 保留字, 实际建表用 Orders
--       id 为 varchar(50), 与时间戳相关, 非自增
create table Orders (
    id                 varchar(50) primary key,
    customer_id        bigint,
    order_date         timestamp,
    loading_port_id    bigint,
    discharge_port_id  bigint,
    status_id          bigint,
    insert_time        timestamp   not null,
    update_time        timestamp   not null
);
comment on table  Orders                    is '订单信息表';
comment on column Orders.id                 is '订单号';
comment on column Orders.customer_id        is '客户ID, 逻辑外键 -> Customer.id';
comment on column Orders.order_date         is '下单时间';
comment on column Orders.loading_port_id    is '起运港, 逻辑外键 -> Port.id';
comment on column Orders.discharge_port_id  is '目的港, 逻辑外键 -> Port.id';
comment on column Orders.status_id          is '订单状态ID, 逻辑外键 -> Order_Status.id';
comment on column Orders.insert_time        is '插入时间';
comment on column Orders.update_time        is '更新时间';

-- 关系模式: Order_Status(id, description)
create table Order_Status (
    id            bigint      generated by default as identity primary key,
    description   varchar(50) unique,
    insert_time   timestamp   not null,
    update_time   timestamp   not null
);
comment on table  Order_Status              is '订单状态字典表';
comment on column Order_Status.id           is '状态ID';
comment on column Order_Status.description  is '状态描述: 1已确认, 2执行中, 3已完成, 4已取消, 其他自定义';
comment on column Order_Status.insert_time  is '创建时间';
comment on column Order_Status.update_time  is '修改时间';

-- =====================================================================
-- 3. 货物信息管理
-- =====================================================================

-- 关系模式: Cargo_Type(id, name, description, weight_kg, volume_m3)
create table Cargo_Type (
    id           bigint        generated by default as identity primary key,
    name         varchar(100),
    description  varchar(255),
    weight_kg    decimal(10,2),
    volume_m3    decimal(10,2),
    insert_time  timestamp     not null,
    update_time  timestamp     not null
);
comment on table  Cargo_Type              is '货物类型表';
comment on column Cargo_Type.id           is '货物类型ID';
comment on column Cargo_Type.name         is '货物名称';
comment on column Cargo_Type.description  is '货物描述';
comment on column Cargo_Type.weight_kg    is '重量(单件)';
comment on column Cargo_Type.volume_m3    is '体积(单件)';
comment on column Cargo_Type.insert_time  is '插入时间';
comment on column Cargo_Type.update_time  is '更新时间';

-- 关系模式: Cargo(id, cargo_type_id, order_id, quantity)
create table Cargo (
    id             bigint      generated by default as identity primary key,
    cargo_type_id  bigint      not null,
    order_id       varchar(50) not null,
    quantity       integer     not null,
    insert_time    timestamp   not null,
    update_time    timestamp   not null
);
comment on table  Cargo                is '货物信息表';
comment on column Cargo.id             is '货物ID';
comment on column Cargo.cargo_type_id  is '货物类型ID, 逻辑外键 -> Cargo_Type.id';
comment on column Cargo.order_id       is '所属订单号, 逻辑外键 -> Orders.id';
comment on column Cargo.quantity       is '数量';
comment on column Cargo.insert_time    is '插入时间';
comment on column Cargo.update_time    is '更新时间';

-- 关系模式: Cargo_Container_Result(id, cargo_id, container_no, quantity)
create table Cargo_Container_Result (
    id            bigint      generated by default as identity primary key,
    cargo_id      bigint      not null,
    container_no  varchar(30) not null,
    quantity      integer     not null,
    insert_time   timestamp   not null,
    update_time   timestamp   not null
);
comment on table  Cargo_Container_Result               is '货物装箱结果表';
comment on column Cargo_Container_Result.id            is '记录ID';
comment on column Cargo_Container_Result.cargo_id      is '货物ID, 逻辑外键 -> Cargo.id';
comment on column Cargo_Container_Result.container_no  is '集装箱号, 逻辑外键 -> Container.no';
comment on column Cargo_Container_Result.quantity      is '装入数量';
comment on column Cargo_Container_Result.insert_time   is '插入时间';
comment on column Cargo_Container_Result.update_time   is '更新时间';

-- =====================================================================
-- 4. 集装箱信息管理
-- =====================================================================

-- 关系模式: Container(no, type_id, owner_id, operator_id, seal_no, status_id,
--                     danger_flag, maritime_flag, carrier_operate, ctr_status_terminal)
create table Container (
    no                   varchar(30) primary key,
    type_id              bigint,
    owner_id             bigint,
    operator_id          bigint,
    seal_no              varchar(50),
    status_id            bigint,
    danger_flag          char(1),
    maritime_flag        char(1),
    carrier_operate      varchar(10),
    ctr_status_terminal  varchar(50),
    insert_time          timestamp not null,
    update_time          timestamp not null
);
comment on table  Container                      is '集装箱信息表';
comment on column Container.no                   is '箱号';
comment on column Container.type_id              is '箱型ID, 逻辑外键 -> Container_Type.id';
comment on column Container.owner_id             is '箱主ID, 逻辑外键 -> Company.id';
comment on column Container.operator_id          is '操作方ID, 逻辑外键 -> Company.id';
comment on column Container.seal_no              is '铅封号';
comment on column Container.status_id            is '当前状态ID, 逻辑外键 -> Container_Status.id';
comment on column Container.danger_flag          is '危险品标识: 0否, 1是';
comment on column Container.maritime_flag        is '海事标识: 0否, 1是';
comment on column Container.carrier_operate      is '船公司操作: 加锁、截关等';
comment on column Container.ctr_status_terminal  is '集装箱堆场状态, 特指在堆场或码头终端的状态';
comment on column Container.insert_time          is '插入时间';
comment on column Container.update_time          is '更新时间';

-- 关系模式: Container_Trailer_Record(id, container_no, track_no,
--                                    dc_in_date, dc_out_date, use_note)
create table Container_Trailer_Record (
    id           bigint      generated by default as identity primary key,
    container_no varchar(30),
    track_no     varchar(30),
    dc_in_date   timestamp,
    dc_out_date  timestamp,
    use_note     varchar(255),
    insert_time  timestamp   not null,
    update_time  timestamp   not null
);
comment on table  Container_Trailer_Record               is '集装箱拖车记录表';
comment on column Container_Trailer_Record.id            is '记录ID';
comment on column Container_Trailer_Record.container_no  is '箱号, 逻辑外键 -> Container.no';
comment on column Container_Trailer_Record.track_no      is '提空箱拖车号, 逻辑外键 -> Trailer.no';
comment on column Container_Trailer_Record.dc_in_date    is '提空箱拖车进场时间';
comment on column Container_Trailer_Record.dc_out_date   is '提空箱拖车出场时间';
comment on column Container_Trailer_Record.use_note      is '箱使用备注';
comment on column Container_Trailer_Record.insert_time   is '插入时间';
comment on column Container_Trailer_Record.update_time   is '更新时间';

-- 关系模式: Container_Type(id, type, size)
create table Container_Type (
    id           bigint      generated by default as identity primary key,
    type         varchar(50),
    size         varchar(20),
    insert_time  timestamp   not null,
    update_time  timestamp   not null
);
comment on table  Container_Type              is '集装箱箱型字典表';
comment on column Container_Type.id           is '箱型ID';
comment on column Container_Type.type         is '箱型类别: 如平板箱、普通箱等';
comment on column Container_Type.size         is '箱尺寸: 如20英尺、40英尺等';
comment on column Container_Type.insert_time  is '创建时间';
comment on column Container_Type.update_time  is '修改时间';

-- 关系模式: Container_Status(id, description_cn, description_en)
create table Container_Status (
    id              bigint      generated by default as identity primary key,
    description_cn  varchar(50) unique,
    description_en  varchar(50) unique,
    insert_time     timestamp   not null,
    update_time     timestamp   not null
);
comment on table  Container_Status                 is '集装箱状态字典表';
comment on column Container_Status.id              is '状态ID';
comment on column Container_Status.description_cn  is '状态中文描述';
comment on column Container_Status.description_en  is '状态英文描述';
comment on column Container_Status.insert_time     is '创建时间';
comment on column Container_Status.update_time     is '修改时间';

-- 关系模式: Company(id, name, code)
create table Company (
    id           bigint       generated by default as identity primary key,
    name         varchar(100),
    code         varchar(20),
    insert_time  timestamp    not null,
    update_time  timestamp    not null
);
comment on table  Company              is '公司信息表';
comment on column Company.id           is '公司ID';
comment on column Company.name         is '公司名称';
comment on column Company.code         is '公司代码: 如CSLU';
comment on column Company.insert_time  is '创建时间';
comment on column Company.update_time  is '修改时间';

-- 关系模式: Trailer(no, phone, name)
create table Trailer (
    no           varchar(30) primary key,
    phone        varchar(30),
    name         varchar(50),
    insert_time  timestamp   not null,
    update_time  timestamp   not null
);
comment on table  Trailer              is '拖车信息表';
comment on column Trailer.no           is '拖车号';
comment on column Trailer.phone        is '联系电话';
comment on column Trailer.name         is '司机姓名';
comment on column Trailer.insert_time  is '创建时间';
comment on column Trailer.update_time  is '修改时间';

-- =====================================================================
-- 5. 集装箱物流信息管理
-- =====================================================================

-- 关系模式: Container_Event(id, container_no, source, voyage_id,
--                           event_place_id, event_status_id, is_esti, event_time)
create table Container_Event (
    id              bigint      generated by default as identity primary key,
    container_no    varchar(30),
    source          char(1),
    voyage_id       bigint,
    event_place_id  bigint,
    event_status_id bigint,
    is_esti         char(1),
    event_time      timestamp,
    insert_time     timestamp   not null,
    update_time     timestamp   not null
);
comment on table  Container_Event                 is '集装箱物流事件表';
comment on column Container_Event.id              is '事件ID';
comment on column Container_Event.container_no    is '箱号, 逻辑外键 -> Container.no';
comment on column Container_Event.source          is '数据来源: 1船公司, 0港区';
comment on column Container_Event.voyage_id       is '航次ID, 逻辑外键 -> Voyage.id';
comment on column Container_Event.event_place_id  is '发生地ID, 逻辑外键 -> 对应的地点/港口表';
comment on column Container_Event.event_status_id is '事件状态ID, 逻辑外键 -> Event_Status.id';
comment on column Container_Event.is_esti         is '是否已发生: N实际发生, Y预计发生';
comment on column Container_Event.event_time      is '状态发生时间';
comment on column Container_Event.insert_time     is '插入时间';
comment on column Container_Event.update_time     is '更新时间';

-- 关系模式: Voyage(id, no, vsl_id, loading_port_id, discharge_port_id)
create table Voyage (
    id                 bigint      generated by default as identity primary key,
    no                 varchar(20),
    vsl_id             bigint,
    loading_port_id    bigint,
    discharge_port_id  bigint,
    insert_time        timestamp   not null,
    update_time        timestamp   not null,
    -- 航次号**不是**全库唯一(航次号由船公司自编, 跨公司重号是常态), 唯一的是
    -- (船, 航次号) 这一对: 同一艘船不能有两个同号航次, 不同船可以重号。
    -- PostgreSQL 的唯一约束不比较 NULL, 所以"没填船"或"没填航次号"的行(如 (null, '2026E001'))
    -- 可以有任意多条, 不会互相冲突 —— 正好对应应用层"任一项为空就跳过查重"的口径。
    constraint uq_voyage_vsl_no unique (vsl_id, no)
);
comment on table  Voyage                    is '航次信息表';
comment on column Voyage.id                 is '航次ID';
comment on column Voyage.no                 is '航次号, 与 vsl_id 一起唯一';
comment on column Voyage.vsl_id             is '船舶ID, 逻辑外键 -> Vessel.id';
comment on column Voyage.loading_port_id    is '起始港口, 逻辑外键 -> Port.id';
comment on column Voyage.discharge_port_id  is '目的港口, 逻辑外键 -> Port.id';
comment on column Voyage.insert_time        is '插入时间';
comment on column Voyage.update_time        is '更新时间';
comment on constraint uq_voyage_vsl_no on Voyage is '同一艘船的航次号不能重复(不同船可以重号)';

-- 关系模式: Event_Status(id, description_cn, description_en)
create table Event_Status (
    id              bigint      generated by default as identity primary key,
    description_cn  varchar(50) unique,
    description_en  varchar(50) unique,
    insert_time     timestamp   not null,
    update_time     timestamp   not null
);
comment on table  Event_Status                 is '集装箱事件状态字典表';
comment on column Event_Status.id              is '状态ID';
comment on column Event_Status.description_cn  is '状态中文描述';
comment on column Event_Status.description_en  is '状态英文描述';
comment on column Event_Status.insert_time     is '创建时间';
comment on column Event_Status.update_time     is '修改时间';

-- =====================================================================
-- 6. 船舶信息管理
-- =====================================================================

-- 关系模式: Vessel(id, name, vessel_type_id, country_id, mmsi, imo, build_year,
--                  owner_company_id, manager_company_id, callsign)
create table Vessel (
    id                  bigint       generated by default as identity primary key,
    name                varchar(100),
    vessel_type_id      bigint,
    country_id          bigint,
    mmsi                varchar(20)  unique,
    imo                 varchar(20)  unique,
    build_year          integer,
    owner_company_id    bigint,
    manager_company_id  bigint,
    callsign            varchar(20)  unique,
    insert_time         timestamp    not null,
    update_time         timestamp    not null
);
comment on table  Vessel                     is '船舶信息表';
comment on column Vessel.id                  is '船舶ID';
comment on column Vessel.name                is '船舶名称';
comment on column Vessel.vessel_type_id      is '船舶类型ID, 逻辑外键 -> Ship_Type.id';
comment on column Vessel.country_id          is '船旗国ID, 逻辑外键 -> Country.id';
comment on column Vessel.mmsi                is '船舶MMSI号码';
comment on column Vessel.imo                 is '船舶IMO号码';
comment on column Vessel.build_year          is '建造年份';
comment on column Vessel.owner_company_id    is '船东ID, 逻辑外键 -> Company.id';
comment on column Vessel.manager_company_id  is '管理公司ID, 逻辑外键 -> Company.id';
comment on column Vessel.callsign            is '呼号, 船舶无线电呼号';
comment on column Vessel.insert_time         is '插入时间';
comment on column Vessel.update_time         is '更新时间';

-- 关系模式: Ship_Type(id, type, GT, length, width, NT, DWT)
-- 注意: GT / NT / DWT 为报告中的字段名, 保留原大小写, 故加双引号
create table Ship_Type (
    id           bigint        generated by default as identity primary key,
    type         varchar(50),
    "GT"         decimal(12,2),
    length       decimal(8,2),
    width        decimal(8,2),
    "NT"         decimal(12,2),
    "DWT"        decimal(12,2),
    insert_time  timestamp     not null,
    update_time  timestamp     not null
);
comment on table  Ship_Type              is '船舶类型字典表';
comment on column Ship_Type.id           is '类型ID';
comment on column Ship_Type.type         is '船舶类型名称: 如集装箱船';
comment on column Ship_Type."GT"         is '总吨, 标准总吨';
comment on column Ship_Type.length       is '长度, 标准长度';
comment on column Ship_Type.width        is '宽度, 标准宽度';
comment on column Ship_Type."NT"         is '净吨, 标准净吨';
comment on column Ship_Type."DWT"        is '载重吨, 标准载重吨';
comment on column Ship_Type.insert_time  is '创建时间';
comment on column Ship_Type.update_time  is '修改时间';

-- =====================================================================
-- 7. 港口信息管理
-- =====================================================================

-- 关系模式: Port(id, unlocode, enname, cnname, country_id, area_id, timezone_id,
--                harbor_size_id, level_id, port_type_id, parent_port_id,
--                latitude, longitude, geom, province, state)
create table Port (
    id              bigint        generated by default as identity primary key,
    unlocode        varchar(10)   unique,
    enname          varchar(100),
    cnname          varchar(100),
    country_id      bigint,
    area_id         bigint,
    timezone_id     bigint,
    harbor_size_id  bigint,
    level_id        bigint,
    port_type_id    bigint,
    parent_port_id  bigint,
    latitude        decimal(9,6),
    longitude       decimal(9,6),
    geom            varchar(255),
    province        varchar(50),
    state           char(1),
    insert_time     timestamp     not null,
    update_time     timestamp     not null
);
comment on table  Port                 is '港口信息表';
comment on column Port.id              is '港口ID';
comment on column Port.unlocode        is '港口五字码';
comment on column Port.enname          is '港口英文名';
comment on column Port.cnname          is '港口中文名';
comment on column Port.country_id      is '港口所在国家ID, 逻辑外键 -> Country.id';
comment on column Port.area_id         is '区域ID, 逻辑外键 -> Area.id';
comment on column Port.timezone_id     is '时区ID, 逻辑外键 -> Timezone.id';
comment on column Port.harbor_size_id  is '港口尺寸ID, 逻辑外键 -> Harbor_Size.id';
comment on column Port.level_id        is '港口级别ID, 逻辑外键 -> Port_Level.id';
comment on column Port.port_type_id    is '港口类型ID, 逻辑外键 -> Port_Type.id';
comment on column Port.parent_port_id  is '母港ID, 逻辑外键 -> Port.id(自反联系)';
comment on column Port.latitude        is '港口中心点纬度';
comment on column Port.longitude       is '港口中心点经度';
comment on column Port.geom            is '港口范围(WKT格式)';
comment on column Port.province        is '港口所在省份';
comment on column Port.state           is '数据状态: 0默认, 1新增, 2修改, 3删除';
comment on column Port.insert_time     is '插入时间';
comment on column Port.update_time     is '更新时间';

-- 关系模式: Country(id, country_code, country_enname, country_cnname)
create table Country (
    id               bigint       generated by default as identity primary key,
    country_code     varchar(10)  unique,
    country_enname   varchar(100),
    country_cnname   varchar(100),
    insert_time      timestamp    not null,
    update_time      timestamp    not null
);
comment on table  Country                 is '国家字典表';
comment on column Country.id              is '国家ID';
comment on column Country.country_code    is '国家代码';
comment on column Country.country_enname  is '国家英文名';
comment on column Country.country_cnname  is '国家中文名';
comment on column Country.insert_time     is '创建时间';
comment on column Country.update_time     is '修改时间';

-- 关系模式: Area(id, area_name)
create table Area (
    id           bigint      generated by default as identity primary key,
    area_name    varchar(50) unique,
    insert_time  timestamp   not null,
    update_time  timestamp   not null
);
comment on table  Area              is '区域字典表';
comment on column Area.id           is '区域ID';
comment on column Area.area_name    is '区域名称: 如North China';
comment on column Area.insert_time  is '创建时间';
comment on column Area.update_time  is '修改时间';

-- 关系模式: Timezone(id, timezone_UTC8, timezone_Asia_Shanghai)
-- 注意: 两个字段名含大写字母, 保留原大小写, 故加双引号
create table Timezone (
    id                       bigint      generated by default as identity primary key,
    "timezone_UTC8"          varchar(20) unique,
    "timezone_Asia_Shanghai" varchar(50) unique,
    insert_time              timestamp   not null,
    update_time              timestamp   not null
);
comment on table  Timezone                           is '时区字典表';
comment on column Timezone.id                        is '时区ID';
comment on column Timezone."timezone_UTC8"           is '港口时区';
comment on column Timezone."timezone_Asia_Shanghai"  is '港口时区(+8)';
comment on column Timezone.insert_time               is '创建时间';
comment on column Timezone.update_time               is '修改时间';

-- 关系模式: Harbor_Size(id, size)
create table Harbor_Size (
    id           bigint      generated by default as identity primary key,
    size         varchar(20),
    insert_time  timestamp   not null,
    update_time  timestamp   not null
);
comment on table  Harbor_Size              is '港口尺寸字典表';
comment on column Harbor_Size.id           is '尺寸ID';
comment on column Harbor_Size.size         is '港口尺寸';
comment on column Harbor_Size.insert_time  is '创建时间';
comment on column Harbor_Size.update_time  is '修改时间';

-- 关系模式: Port_Level(id, level)
create table Port_Level (
    id           bigint      generated by default as identity primary key,
    level        integer,
    insert_time  timestamp   not null,
    update_time  timestamp   not null
);
comment on table  Port_Level              is '港口级别字典表';
comment on column Port_Level.id           is '级别ID';
comment on column Port_Level.level        is '港口级别';
comment on column Port_Level.insert_time  is '创建时间';
comment on column Port_Level.update_time  is '修改时间';

-- 关系模式: Port_Type(id, type)
create table Port_Type (
    id           bigint      generated by default as identity primary key,
    type         varchar(20),
    insert_time  timestamp   not null,
    update_time  timestamp   not null
);
comment on table  Port_Type              is '港口类型字典表';
comment on column Port_Type.id           is '类型ID';
comment on column Port_Type.type         is '港口类型: 1系统规范港口, 2用户自定义港口';
comment on column Port_Type.insert_time  is '创建时间';
comment on column Port_Type.update_time  is '修改时间';

-- =====================================================================
-- 8. 系统日志与审计
-- =====================================================================

-- 关系模式: User(id, username, password, real_name, phone, status)
-- 注意: 报告中表名为 User, 为避免 SQL 保留字, 实际建表用 Users
--       ⚠️ 报告**未标注** id 自增, 但这里**改成了自增** —— 与其余 24 张自增表保持一致。
--          原本照抄成 bigint primary key, 后端就得用雪花算法生成 id, 结果同一种主键
--          在系统里有两套生成方式, 而且雪花号是 19 位、前端 parseInt 会丢精度。
--          ⚠️ 这次改动要和实体上的 @TableId(type = IdType.AUTO) 同步改, 只改一边会错。
create table Users (
    id           bigint generated by default as identity primary key,
    username     varchar(50) unique,
    password     varchar(255),
    real_name    varchar(100),
    phone        varchar(30),
    status       char(1),
    insert_time  timestamp not null,
    update_time  timestamp not null
);
comment on table  Users              is '系统用户表';
comment on column Users.id           is '用户ID';
comment on column Users.username     is '登录名';
comment on column Users.password     is '密码/密码哈希';
comment on column Users.real_name    is '真实姓名';
comment on column Users.phone        is '电话';
comment on column Users.status       is '账号状态: 0正常, 1冻结, 2已删除';
comment on column Users.insert_time  is '创建时间';
comment on column Users.update_time  is '修改时间';

-- 关系模式: Operation_Type(id, type)
-- 注意: 报告未标注 id 自增, 这里同 Users 一并改成自增(理由见上面 Users 那段)。
--       1~5 由 operation-type-data.sql 显式指定(内置类型), 之后新建的从 6 开始。
create table Operation_Type (
    id           bigint generated by default as identity primary key,
    type         varchar(50) unique,
    insert_time  timestamp not null,
    update_time  timestamp not null
);
comment on table  Operation_Type              is '操作类型字典表';
comment on column Operation_Type.id           is '类型ID';
comment on column Operation_Type.type         is '操作类型: 新增、修改、删除';
comment on column Operation_Type.insert_time  is '创建时间';
comment on column Operation_Type.update_time  is '修改时间';

-- 关系模式: Log(id, user_id, type_id, operation_time, result_status,
--                error_message, target_table, target_id, before_value, after_value)
-- 注意: 报告未标注 id 自增, 这里同 Users 一并改成自增(理由见上面 Users 那段)。
create table Log (
    id              bigint generated by default as identity primary key,
    user_id         bigint,
    type_id         bigint,
    operation_time  timestamp,
    result_status   char(1),
    error_message   varchar(500),
    target_table    varchar(50),
    target_id       varchar(50),
    before_value    text,
    after_value     text,
    insert_time     timestamp not null,
    update_time     timestamp not null
);
comment on table  Log                 is '操作日志表';
comment on column Log.id              is '日志ID';
comment on column Log.user_id         is '用户ID, 逻辑外键 -> Users.id';
comment on column Log.type_id         is '操作类型ID, 逻辑外键 -> Operation_Type.id';
comment on column Log.operation_time  is '操作时间';
comment on column Log.result_status   is '执行结果: 错误为0, 正确为1';
comment on column Log.error_message   is '错误信息';
comment on column Log.target_table    is '目标表名';
comment on column Log.target_id       is '目标记录主键';
comment on column Log.before_value    is '操作前数据';
comment on column Log.after_value     is '操作后数据';
comment on column Log.insert_time     is '插入时间';
comment on column Log.update_time     is '更新时间';

-- =====================================================================
-- 逻辑外键索引
-- 报告中所有"逻辑外键"未建立物理约束, 此处为关联字段建立索引以保证连接查询性能
-- =====================================================================

create index idx_customer_status_id              on Customer (status_id);

-- name / qualification 是前缀匹配(name LIKE 'x%')。默认排序规则下, 普通 btree 索引
-- 撑不起 LIKE, 必须指定 varchar_pattern_ops 才会被查询用到。
create index idx_customer_name                   on Customer (name varchar_pattern_ops);
create index idx_customer_qualification          on Customer (qualification varchar_pattern_ops);



-- 资质有效期是区间查询(>= / <=), 普通 btree 即可
create index idx_customer_qualification_valid_to on Customer (qualification_valid_to);

create index idx_orders_customer_id              on Orders (customer_id);
create index idx_orders_loading_port_id          on Orders (loading_port_id);
create index idx_orders_discharge_port_id        on Orders (discharge_port_id);
create index idx_orders_status_id                on Orders (status_id);

create index idx_cargo_cargo_type_id             on Cargo (cargo_type_id);
create index idx_cargo_order_id                  on Cargo (order_id);

-- 货物种类列表按名称前缀搜索(/cargo-types?name=)。和 Customer.name / Port.cnname 同理:
-- 默认排序规则下普通 btree 撑不起 LIKE, 必须指定 varchar_pattern_ops 才会被查询用到。
create index idx_cargo_type_name_pattern         on Cargo_Type (name varchar_pattern_ops);

-- 公司按名称 / 代码前缀搜索(/companies?keyword= 和 /companies/options?keyword= 都用它)。
-- 这两个索引是为了让"新增集装箱时选箱主/操作方"能搜出来, 不用盲填 id。
-- 同理, name 和 code 在库里都没有唯一约束, 这两个是纯粹为 LIKE 建的模式索引。
create index idx_company_name_pattern            on Company (name varchar_pattern_ops);
create index idx_company_code_pattern            on Company (code varchar_pattern_ops);

create index idx_cargo_container_result_cargo_id     on Cargo_Container_Result (cargo_id);
create index idx_cargo_container_result_container_no on Cargo_Container_Result (container_no);

create index idx_container_type_id               on Container (type_id);
create index idx_container_owner_id              on Container (owner_id);
create index idx_container_operator_id           on Container (operator_id);
create index idx_container_status_id             on Container (status_id);

create index idx_ctr_trailer_record_container_no on Container_Trailer_Record (container_no);
create index idx_ctr_trailer_record_track_no     on Container_Trailer_Record (track_no);

-- 下面四个是**给前缀搜索用的模式索引**, 和上面那两个外键索引是两回事:
-- 上面那两个服务等值查询(=), 服务不了 LIKE, 所以同一列上再建一个 varchar_pattern_ops 变体。
-- 用在: 提空箱登记的列表(箱号/拖车号前缀)、拖车的列表和下拉框(拖车号/司机姓名前缀)。
create index idx_ctr_trailer_record_container_no_pattern on Container_Trailer_Record (container_no varchar_pattern_ops);
create index idx_ctr_trailer_record_track_no_pattern     on Container_Trailer_Record (track_no varchar_pattern_ops);
create index idx_trailer_no_pattern                      on Trailer (no varchar_pattern_ops);
create index idx_trailer_name_pattern                    on Trailer (name varchar_pattern_ops);

create index idx_container_event_container_no    on Container_Event (container_no);
create index idx_container_event_voyage_id       on Container_Event (voyage_id);
create index idx_container_event_place_id        on Container_Event (event_place_id);
create index idx_container_event_status_id       on Container_Event (event_status_id);

create index idx_voyage_vsl_id                   on Voyage (vsl_id);
create index idx_voyage_loading_port_id          on Voyage (loading_port_id);
create index idx_voyage_discharge_port_id        on Voyage (discharge_port_id);

create index idx_vessel_vessel_type_id           on Vessel (vessel_type_id);
create index idx_vessel_country_id               on Vessel (country_id);
create index idx_vessel_owner_company_id         on Vessel (owner_company_id);
create index idx_vessel_manager_company_id       on Vessel (manager_company_id);

create index idx_port_country_id                 on Port (country_id);
create index idx_port_area_id                    on Port (area_id);
create index idx_port_timezone_id                on Port (timezone_id);
create index idx_port_harbor_size_id             on Port (harbor_size_id);
create index idx_port_level_id                   on Port (level_id);
create index idx_port_port_type_id               on Port (port_type_id);
create index idx_port_parent_port_id             on Port (parent_port_id);

-- 船舶和港口列表的**前缀搜索**索引(和其它模块同一套: 默认 opclass 的索引撑不起 LIKE)。
--   vessel: keyword 同时匹配 船名 / MMSI / IMO
--   port  : keyword 同时匹配 五字码 / 中文名 / 英文名 —— 其中 enname / cnname 两个
--           上面已经建过了(给 /ports/options 用的), 这里只补缺的那个。
-- mmsi / imo / unlocode 原本就有 UNIQUE 索引, 但那个服务等值查询, 所以另建模式索引。
create index idx_vessel_name_pattern     on Vessel (name varchar_pattern_ops);
create index idx_vessel_mmsi_pattern     on Vessel (mmsi varchar_pattern_ops);
create index idx_vessel_imo_pattern      on Vessel (imo varchar_pattern_ops);
create index idx_port_unlocode_pattern   on Port (unlocode varchar_pattern_ops);

-- 📌 其余那几张小字典(country / area / timezone / ship_type / harbor_size /
--    port_level / port_type)最多十来行, 前缀搜索直接全表扫就行, **故意不加索引** ——
--    给它们建索引属于净负担(占空间、拖慢写入), 换不来任何收益。

-- 下面两个不是外键索引, 是给港口下拉框的前缀搜索用的(/ports/options 按中英文名前缀匹配)。
-- 和 Customer.name / qualification 同理: 默认排序规则下普通 btree 撑不起 LIKE,
-- 必须指定 varchar_pattern_ops 才会被查询用到。
-- unlocode 不重复建: 它已经有 unique 约束自带的索引, 等值查询够用。
create index idx_port_enname_pattern             on Port (enname varchar_pattern_ops);
create index idx_port_cnname_pattern             on Port (cnname varchar_pattern_ops);

create index idx_log_user_id                     on Log (user_id);
create index idx_log_type_id                     on Log (type_id);

-- =====================================================================
-- 时间戳触发器
--
-- 规则(对应头部说明第 8 条):
--   INSERT: insert_time / update_time 为空则填当前北京时间; 后端传了值则保留后端的
--   UPDATE: insert_time 锁死不变(始终等于创建时刻);
--           update_time 若后端显式改成了不同的值, 尊重后端的值;
--                       否则整行数据有实质变化时刷新为当前北京时间,
--                       整行无实质变化时保持原值。
--
-- 时区固定为 Asia/Shanghai, 通过 now() at time zone 转换,
-- 不依赖数据库服务器的 timezone 设置。
-- =====================================================================

create or replace function set_time_fields() returns trigger as $$
begin
    if tg_op = 'INSERT' then
        if new.insert_time is null then
            new.insert_time := now() at time zone 'Asia/Shanghai';
        end if;
        if new.update_time is null then
            new.update_time := now() at time zone 'Asia/Shanghai';
        end if;
        return new;
    end if;

    -- 以下为 UPDATE 分支
    -- 创建时刻锁死, 不允许被修改
    new.insert_time := old.insert_time;

    if new.update_time is distinct from old.update_time then
        -- 后端显式修改了 update_time, 尊重后端的值
        return new;
    end if;

    -- 走到这里说明 insert_time 与 update_time 都与 old 相同,
    -- 因此整行比较的结果只反映其他字段是否真的发生了变化
    if new is distinct from old then
        new.update_time := now() at time zone 'Asia/Shanghai';
    else
        new.update_time := old.update_time;
    end if;

    return new;
end;
$$ language plpgsql;

create trigger trg_set_time_customer                 before insert or update on Customer                 for each row execute function set_time_fields();
create trigger trg_set_time_customer_status          before insert or update on Customer_Status          for each row execute function set_time_fields();
create trigger trg_set_time_orders                   before insert or update on Orders                   for each row execute function set_time_fields();
create trigger trg_set_time_order_status             before insert or update on Order_Status             for each row execute function set_time_fields();
create trigger trg_set_time_cargo_type               before insert or update on Cargo_Type               for each row execute function set_time_fields();
create trigger trg_set_time_cargo                    before insert or update on Cargo                    for each row execute function set_time_fields();
create trigger trg_set_time_cargo_container_result   before insert or update on Cargo_Container_Result   for each row execute function set_time_fields();
create trigger trg_set_time_container                before insert or update on Container                for each row execute function set_time_fields();
create trigger trg_set_time_container_trailer_record before insert or update on Container_Trailer_Record for each row execute function set_time_fields();
create trigger trg_set_time_container_type           before insert or update on Container_Type           for each row execute function set_time_fields();
create trigger trg_set_time_container_status         before insert or update on Container_Status         for each row execute function set_time_fields();
create trigger trg_set_time_company                  before insert or update on Company                  for each row execute function set_time_fields();
create trigger trg_set_time_trailer                  before insert or update on Trailer                  for each row execute function set_time_fields();
create trigger trg_set_time_container_event          before insert or update on Container_Event          for each row execute function set_time_fields();
create trigger trg_set_time_voyage                   before insert or update on Voyage                   for each row execute function set_time_fields();
create trigger trg_set_time_event_status             before insert or update on Event_Status             for each row execute function set_time_fields();
create trigger trg_set_time_vessel                   before insert or update on Vessel                   for each row execute function set_time_fields();
create trigger trg_set_time_ship_type                before insert or update on Ship_Type                for each row execute function set_time_fields();
create trigger trg_set_time_port                     before insert or update on Port                     for each row execute function set_time_fields();
create trigger trg_set_time_country                  before insert or update on Country                  for each row execute function set_time_fields();
create trigger trg_set_time_area                     before insert or update on Area                     for each row execute function set_time_fields();
create trigger trg_set_time_timezone                 before insert or update on Timezone                 for each row execute function set_time_fields();
create trigger trg_set_time_harbor_size              before insert or update on Harbor_Size              for each row execute function set_time_fields();
create trigger trg_set_time_port_level               before insert or update on Port_Level               for each row execute function set_time_fields();
create trigger trg_set_time_port_type                before insert or update on Port_Type                for each row execute function set_time_fields();
create trigger trg_set_time_users                    before insert or update on Users                    for each row execute function set_time_fields();
create trigger trg_set_time_operation_type           before insert or update on Operation_Type           for each row execute function set_time_fields();
create trigger trg_set_time_log                      before insert or update on Log                      for each row execute function set_time_fields();

commit;
