-- =====================================================================
--  操作类型字典 初始数据 (PostgreSQL)
--
--  执行前提: 已执行 initial.sql。本表不依赖其他表。被 log.type_id 引用。
--
--  ⚠️ **这五行就是全部, id 必须正好是 1~5, 值和 id 都不能改。**
--     它们和 Java 枚举 com.test.hangyun.pojo.enums.OpType 一一对应,
--     操作日志切面就是按这些 id 写 Log.type_id 的。
--
--        1 = INSERT   新增          《报告》数据字典原本就有的三个之一
--        2 = UPDATE   修改          《报告》数据字典原本就有的三个之一
--        3 = DELETE   删除(含批量)  《报告》数据字典原本就有的三个之一
--        4 = EXPORT   导出 Excel    本次补充: 设计文档 5.4 要求"导出也要留痕"
--        5 = LOGIN    登录          本次补充: 审计需要知道谁什么时候进过系统
--
--  ⚠️ **这张表不提供新增和删除接口**(只有查询 + 修改), 理由:
--     · 删掉一行 —— 代码里的 @OpLog 仍按那个 id 写日志, 新日志在 v_operation_log 里
--       JOIN 不出类型名, "操作类型"那列会变空白, 而且不会有任何报错提示你
--     · 加一行   —— 没有任何 @OpLog 会用到它, 纯属多余
--     通过 PUT /operation-types/{id} 改文字是允许的, 不影响 id 与代码的对应关系。
--
--  ⚠️ **如果你之前已经跑过本文件(那时值是中文的 新增/修改/删除/导出/登录)**:
--     insert 配 on conflict do nothing **不会更新已有的行**, 要手工跑一遍下面的 update:
--
--        update operation_type set type = 'INSERT' where id = 1;
--        update operation_type set type = 'UPDATE' where id = 2;
--        update operation_type set type = 'DELETE' where id = 3;
--        update operation_type set type = 'EXPORT' where id = 4;
--        update operation_type set type = 'LOGIN'  where id = 5;
--
--  编写约定: insert_time / update_time 留 null 交给触发器; id 显式指定 +
--            on conflict do nothing 保证可重复执行; 末尾同步自增序列。
--  ⚠️ 本表 id 是 `generated by default as identity`(**自增**)。
--     显式插入 1~5 **不会推进序列**, 不跑末尾的 setval 的话, 页面上想改 id 时
--     会拿到已经占用的号。同步之后新增的号从 6 开始(虽然接口不提供新增)。
-- =====================================================================

begin;

insert into operation_type (id, type) values
    (1, 'INSERT'),
    (2, 'UPDATE'),
    (3, 'DELETE'),
    (4, 'EXPORT'),
    (5, 'LOGIN')
on conflict do nothing;

-- 显式插入 identity 列不会移动序列, 这里手动同步。
-- setval(..., n, false) 表示下一次 nextval 返回 n, 所以取 max(id) + 1。
select setval(
    pg_get_serial_sequence('operation_type', 'id'),
    coalesce((select max(id) from operation_type), 0) + 1,
    false
);

commit;
