-- =====================================================================
--  订单状态字典 初始数据 (PostgreSQL)
--
--  执行前提: 已执行 initial.sql —— order_status 表和 set_time_fields()
--            触发器都必须已经存在, 本脚本不负责建表。
--
--  写入四条订单状态, id 显式指定为 1 / 2 / 3 / 4, 与 Order_Status 的列注释
--  "1已确认, 2执行中, 3已完成, 4已取消" 以及 orders.status_id 的取值保持一致。
--  其中 4(已取消)还被订单逻辑删除复用(见 OrderServiceImpl#delete)。
--
--  编写约定:
--    1. insert_time / update_time 不写值, 留 null 交给 set_time_fields() 触发器
--       填北京时间, 与后端 Service 的行为一致。
--    2. 用 on conflict do nothing, 保证脚本可以重复执行 —— 重复跑不会报唯一键冲突。
--    3. id 是 generated by default as identity: 显式插入 id 不会推进自增序列,
--       所以末尾必须把序列对齐到 max(id) + 1, 否则后端新增状态时会生成 id=1 并撞主键。
-- =====================================================================

begin;

insert into order_status (id, description) values
    (1, '已确认'),
    (2, '执行中'),
    (3, '已完成'),
    (4, '已取消')
on conflict do nothing;

-- 显式插入 identity 列不会移动序列, 这里手动同步。
-- setval(..., n, false) 表示下一次 nextval 返回 n, 所以取 max(id) + 1。
select setval(
    pg_get_serial_sequence('order_status', 'id'),
    coalesce((select max(id) from order_status), 0) + 1,
    false
);

commit;
