-- =====================================================================
--  港口表 模拟数据 (PostgreSQL)
--
--  执行前提: 已执行 initial.sql —— port 表和 set_time_fields() 触发器都已存在。
--            另外 country / area / timezone / harbor_size / port_type 这几张字典表
--            **目前没有任何数据**, 所以下面都留空了, 不要填。
--
--  十条港口, 五字码(UN/LOCODE)、中英文名都取自真实的港口编码。
--  用途是让 GET /ports/options 能搜出东西来; 联调时可以这样验证:
--    · keyword=上海   → 命中"上海港"
--    · keyword=CNS    → 命中 CNSHA / CNSZX(两个), 验证五字码也能搜
--    · keyword=CN     → 命中全部 8 个中国港口
--    · keyword=Shang  → 命中"Shanghai", 验证英文名也能搜
--    · 不传 keyword   → 返回前 9 条(第 10 条是已删除的, 不出现)
--
--  ⚠️ 第 10 条是**故意标成已删除(state = '3')** 的, 用来验证查询会自动过滤掉它。
--     如果只想要 10 条干净数据, 把它的 state 改成 '0' 即可。
--
--  编写约定:
--    1. 坐标是**约值**, 仅用于展示; 正式数据请按实际港口坐标替换。
--    2. insert_time / update_time 不写值, 留 null 交给 set_time_fields() 触发器填北京时间。
--    3. id 显式指定 + on conflict do nothing, 保证脚本可以重复执行。
--    4. id 是 generated by default as identity: 显式插入 id 不会推进自增序列,
--       所以末尾必须把序列对齐到 max(id) + 1。
-- =====================================================================

begin;

insert into port (id, unlocode, enname, cnname, province, latitude, longitude, state) values
    (1,  'CNSHA',  'Shanghai',    '上海港',   '上海市',   31.230000, 121.490000, '0'),
    (2,  'CNNGB',  'Ningbo',      '宁波港',   '浙江省',   29.870000, 121.550000, '0'),
    (3,  'CNSZX',  'Shenzhen',    '深圳港',   '广东省',   22.500000, 113.880000, '0'),
    (4,  'CNTAO',  'Qingdao',     '青岛港',   '山东省',   36.070000, 120.320000, '0'),
    (5,  'CNTXG',  'Tianjin',     '天津港',   '天津市',   38.990000, 117.740000, '0'),
    (6,  'CNXMN',  'Xiamen',      '厦门港',   '福建省',   24.450000, 118.070000, '0'),
    (7,  'CNDLC',  'Dalian',      '大连港',   '辽宁省',   38.920000, 121.630000, '0'),
    (8,  'CNLYG',  'Lianyungang', '连云港港', '江苏省',   34.750000, 119.450000, '0'),
    (9,  'USLAX',  'Los Angeles', '洛杉矶港', 'California', 33.740000, -118.270000, '0'),
    (10, 'SGSIN',  'Singapore',   '新加坡港', null,       1.290000,  103.850000, '3')
on conflict do nothing;

-- 显式插入 identity 列不会移动序列, 这里手动同步。
-- setval(..., n, false) 表示下一次 nextval 返回 n, 所以取 max(id) + 1。
select setval(
    pg_get_serial_sequence('port', 'id'),
    coalesce((select max(id) from port), 0) + 1,
    false
);

commit;
