-- =====================================================================
--  系统用户 初始数据 (PostgreSQL)
--
--  执行前提: 已执行 initial.sql。本表不依赖其他表。
--
--  两个账号(登录时的密码就是下面注释里的明文):
--
--      id=1  admin     / admin123    内置管理员 —— **不可删除、不可冻结**
--      id=2  zhangmin  / 123456      普通业务员(演示用)
--
--  ⚠️ password 存的是 **BCrypt 哈希, 不是明文**。这两个哈希是用本项目的
--     new BCryptPasswordEncoder(10).encode(...) 真算出来的, 并当场用 matches() 验证过,
--     不是随手编的字符串 —— 编的字符串会让登录永远失败。
--     BCrypt 哈希**自带盐和强度**(形如 $2a$10$...), 所以表里**不需要额外的 salt 列**,
--     校验时把明文和这一整串一起交给 PasswordEncoder.matches(...) 即可。
--
--  ⚠️ 关于 id: Users.id 是 IdType.ASSIGN_ID(雪花算法), 正常新增的用户会是 19 位大数。
--     这里**手工指定成 1/2**, 是为了让 admin 固定是 id=1 —— 代码里"内置管理员不允许删除"
--     就是按这个 id 判断的(UserConstants.BUILTIN_ADMIN_ID)。
--     页面上新建的用户由后端生成雪花 id, 和 1/2 不会撞。
--
--  编写约定: insert_time / update_time 留 null 交给触发器; id 显式指定 +
--            on conflict do nothing 保证可重复执行; 末尾同步自增序列。
--  ⚠️ 本表 id 是 `generated by default as identity`(**自增**)。
--     **显式插入 id 不会推进序列** —— 不跑末尾的 setval, 页面上新建用户时会拿到
--     id=1/2, 直接撞主键报 500。所以最后那句 setval 不能省。
-- =====================================================================

begin;

insert into users (id, username, password, real_name, phone, status) values
    (1, 'admin',    '$2a$10$WxrYhBZ8.pZ01RPOFctqi..Ngu5Y6zqZXuH1U2fSEWzkSSA.1zhIC', '系统管理员', '13800000000', '0'),
    (2, 'zhangmin', '$2a$10$.OmBgIv8TXlLlBMR.0WTuueV/gue0BjNDc.h/poXI9qjcTTtfgKha', '张敏',       '13900000001', '0')
on conflict do nothing;

-- 显式插入 identity 列不会移动序列, 这里手动同步。
-- setval(..., n, false) 表示下一次 nextval 返回 n, 所以取 max(id) + 1。
select setval(
    pg_get_serial_sequence('users', 'id'),
    coalesce((select max(id) from users), 0) + 1,
    false
);

commit;
