package com.test.hangyun.pojo.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * 货物信息表 cargo 。
 * <p>
 * 报告中的关系模式: Cargo(id, cargo_type_id, order_id, quantity)
 * <p>
 * 注意主键类型: 建表脚本里 id 是 {@code generated by default as identity}, 也就是**自增**,
 * 所以用 {@code IdType.AUTO}。设计文档 3.4 / 5.2 里写的"Cargo 不自增、用 ASSIGN_ID"
 * 与建表脚本不符 —— 以脚本为准。
 */
@Data
@TableName("cargo")
public class Cargo {

    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /** 货物种类ID, 逻辑外键 -> cargo_type.id */
    private Long cargoTypeId;

    /** 所属订单号, 逻辑外键 -> orders.id (varchar) */
    private String orderId;

    /** 数量 */
    private Integer quantity;

    /**
     * 插入时间。
     * 由数据库触发器 set_time_fields() 维护, 应用层一律不要赋值, 留 null 即可。
     */
    private LocalDateTime insertTime;

    /**
     * 修改时间。
     * 由数据库触发器 set_time_fields() 维护, 应用层一律不要赋值, 留 null 即可。
     */
    private LocalDateTime updateTime;
}
